config/routes.rb
Rails.application.routes.draw do
	
  root               	 'static_pages#home'
  get   	'help'    => 'static_pages#help'
  get   	'about'   => 'static_pages#about'
  get   	'contact' => 'static_pages#contact'
  get   	'signup'  => 'users#new'
	get			'login'		=> 'sessions#new'
	post		'login'		=> 'sessions#create'
	delete	'logout'	=> 'sessions#destroy'
  
  resources    :users do
		member do
			get :following, :followers
		end
	end
	resources 	 :account_activations, 	only: [:edit]
	resources 	 :password_resets, 			only: [:new, :create, :edit, :update]
	resources 	 :microposts, 					only: [:create, :destroy]
	resources 	 :relationships,				only: [:create, :destroy]
	
	get '/uploads/grid/micropost/picture/:id/:filename' => 'microposts#picture'
end

app/views/layouts/_footer.html.slim
footer class="footer"
	small
		| The #{link_to "Ruby on Rails Tutorial", "http://www.railstutorial.org"}
		| by #{link_to "Michael Hartl", "http://www.michaelhartl.com"}
	nav
		ul
			li =link_to "About",   about_path
			li =link_to "Contact", contact_path
			li =link_to "News", "http://news.railstutorial.org"

app/views/layouts/_header.html.slim
header class="navbar navbar-fixed-top navbar-inverse"
	.container
		= link_to "sample app", root_path, id: 'logo'
		nav
			ui class="nav navbar-nav pull-right"
				li #{link_to "Home", 	root_path}
				li #{link_to "Help", 	help_path}
				- if logged_in?
					li = link_to "Users", users_path
					li.dropdown
						a.dropdown-toggle href="#" data-toggle="dropdown"
							| Account
							b.caret
						ul.dropdown-menu
							li #{link_to "Profile", current_user}
							li #{link_to "Settings", edit_user_path(current_user)}
							li.divider
							li = link_to "Log out", logout_path, method: "delete"
				-	else
					li =link_to "Log in", login_path

app/views/layouts/_shim.html.slim
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.slim
doctype html
html
	head
		title #{full_title(yield(:title))}
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
		= render partial="layouts/shim"
	body
		= render partial="layouts/header"
		.container
			- flash.each do |message_type, message|
			  div[class="alert alert-#{message_type}"] #{message}
			= yield
			= render partial="layouts/footer"
			/ = debug(params) if Rails.env.development?